### ISSUE TITLE
[BUG] PLEX for WINDOWS, PLEX MEDIA PLAYER и PLEX FOR WEB не воспроизводит трейлеры КИНОПОИСК с плагином КИНОПОИСК

### ISSUE THREAD

**Issue by Denisamir** [amirotin/Kinopoisk.bundle#15]
Проблема с невозможностью воспроизвести любые трейлеры с получением ошибки есть на всех версиях плагина КИНОПОИСК. (Плагин вместе с сервером PLEX установлен под WINDOWS 10 (обновление 1909)) Проблема сохраняется и при запуске под WINDOWS PLEX FOR WEB(браузер EDGE и прочие браузеры, могу протестить любой ).
У меня версия PLEX SERVER самая новая и актуальная 1.18.8.2468. Куплен PLEX PASS. Сервер установлен на том же WINDOWS компьютере, по железу компьютер далеко не новый.
Имя сервера “КОМПЬЮТЕР ДЕНИСА”
Версия агента кинопоиска “КИНОПОИСК 2.0” (если уточнять, то 2.0.7, но проблема была и на предыдущих версиях плагина.
Проблема проявляется на всех последних версиях клиентов кроме APPLE IOS и APPLE TVOS.
PLEX FOR WINDOWS версия 1.6.3.1009-57cf57c8
PLEX MEDIA PLAYER for WINDOWS версия 4.24.1
PLEX WEB версия 4.26 (браузер MICROSOFT EDGE последний)
Проблемы нет только в PLEX FOR APPLE IOS и APPLE TVOS.
В PLEX под WEB некоторые импортные трейлеры на английском языке проигрываются.
В PLEX MEDIA PLAYER for WINDOWS ошибка следующая: “Ошибка воспроизведения: При попытке воспроизведения «Трейлер (дублированный)» произошла ошибка.”
В PLEX FOR WINDOWS ошибка следующая: “Произошла неизвестная ошибка (-13) Код ошибки: -13”
В PLEX WEB ошибка следующая: “При попытке воспроизведения «Трейлер (дублированный)» произошла ошибка. Код ошибки: s1001 (Сеть)”.
Для воспроизведения ошибки нужно нажать кнопку ВОСПРОИЗВЕСТИ ТРЕЙЛЕР любого фильма библиотеки, либо самостоятельно выбрать трейлер и нажать на конкретный трейлер.
Проблема воспроизводится во всех имеющихся в библиотеке фильмах.
![PLEX_кнопка_воспроизведения трейлера после которой вылазит ошибка](https://user-images.githubusercontent.com/61730320/75769675-6757a300-5d68-11ea-9432-eb38e0dafb51.png)

![PLEX_ошибка_воспроизведения_трейлера_КИНОПОИСК_в_PLEX_for_WINDOWS](https://user-images.githubusercontent.com/61730320/75769666-66267600-5d68-11ea-8223-b2f96ae43a04.png)
![PLEX_ошибка_воспроизведения_трейлера_КИНОПОИСК_в_PLEX_MEDIA_PLAYER_for_WINDOWS](https://user-images.githubusercontent.com/61730320/75769672-6757a300-5d68-11ea-9f93-7ea46d9957bc.png)

![PLEX_ошибка_воспроизведения_трейлера_КИНОПОИСК_в_PLEX_WEB PNG](https://user-images.githubusercontent.com/61730320/75769678-6888d000-5d68-11ea-8d84-21a418dcc50a.png)

**Comment by advokatb** [comment]
Могу добавить, что из-за этого бага не воспроизводились фильмы на телевизоре Samsung SmartTV 2012 года.
Пришлось отключить трейлеры, и проблема ушла.

**Comment by Denisamir** [comment]
Сами фильмы у меня конкретно на WINDOWS воспроизводятся. На моём телевизоре SONY 2013 модельного года был PLEX внутри SMART TV, но его удалили в середине 2019 года вместе с  кончиной магазина приложений VEWD TV STORE, поэтому на телевизоре проверить не могу, на APPLE TV в PLEX фильмы идут с установленным плагином от КИНОПОИСК. Да и вроде фильмы никак не связаны с плагином от Кинопоиск.

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и запустите обновление метаданных.
