### ISSUE TITLE
[BUG]В версии 2.0.7 ко всем фильмам подтягивает метаданные от одного фильма

### ISSUE THREAD

**Issue by FullSilence** [amirotin/Kinopoisk.bundle#18]
В версии 2.0.7 ко всем фильмам подтягивает метаданные от одного фильма "И никого не стало" от 2015 года. Ручное сопоставление не помогает, он тут же обновляет МЕТА и возвращает неверные данные.
![BUG](https://user-images.githubusercontent.com/16937393/76139781-c36e4000-6064-11ea-9e33-ec1b4b0a3687.png)

В версии 2.0.0 все отлично.

**Comment by anvme** [comment]
Просьба оформить баг по шаблону как минимум

**Comment by Nickulous** [comment]
Переустановите плагин. Проблема только у вас

**Comment by nikolaevi** [comment]
Очень глючная версия 2.0.7, предыдущая работала нормально. Пробовал переустановить три раза - не помогло. Попробовал вернуть старую версию - тоже самое:
- находит фильм на кинопоиске, но ничего не может подгрузить, просто крутится "кружок" и всё

**Comment by yuryavd** [comment]
Такая же проблема

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и возможно потребуется обновить метаданные.
Сообщите пожалуйста, если проблема актуальна
