### ISSUE TITLE
[BUG] Некорректная версия Кинопоиска в агентах

### ISSUE THREAD

**Issue by anvme** [amirotin/Kinopoisk.bundle#19]
**Описание ошибки**
В настройках в агентах выводится некорректная версия Кинопоиска в агентах

**Шаги для вопроизведения ошибки**
1. Перейти в настройки:настройки-агенты
2. Нажать фильмы-кинопоиск (I)
3. Версия расходится с версией в настойки-> управление:подключаемые модули

**Ожидание**
Соответствие версий 

**Скриншоты**
<img width="1344" alt="plex_" src="https://user-images.githubusercontent.com/56738034/76141405-eacd0900-6074-11ea-8b55-021846b4154d.png">

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Windows
 - Браузер: chrome
 - Версия PLEX: 1.18.8.2468
 - Версия агента кинопоиск: Kinopoisk #v2.0.7

**Дополнительная информация**
Отсутствует

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, в ней убрана эта сноска для избежания путаницы
