### ISSUE TITLE
[BUG] Постер от другого фильма

### ISSUE THREAD

**Issue by anvme** [amirotin/Kinopoisk.bundle#21]
**Описание ошибки**
Забирается постер который в указанном фильме отсутствует.
Ссылка на страницу фильма на КП https://www.kinopoisk.ru/film/647291/
Постера дисней нет
Проверка проводилась также на отдельно созданной библиотеке с обновлением метаданных по этому фильма. Результат аналогичный.

**Ожидание**
Отсутствие постеров от других фильмов

**Скриншоты**
Имя файла Zолушка [Cinderella] (2012) [1080p-x264].mkv
<img width="724" alt="plex_1" src="https://user-images.githubusercontent.com/56738034/76142106-8d888600-607b-11ea-98a3-9e410ba32c39.png">

Страница фильма в плеске с постром дисней
<img width="1153" alt="plex_2" src="https://user-images.githubusercontent.com/56738034/76142079-426e7300-607b-11ea-82c7-bc31c6b8b458.png">

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Windows
 - Браузер: chrome
 - Версия PLEX: 1.18.8.2468
 - Версия агента кинопоиск: Kinopoisk #v2.0.7

**Дополнительная информация**
нет

**Comment by Nickulous** [comment]
Переустанови плагин, у меня все нормально отображает. Только что проверил

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и возможно потребуется обновить метаданные.
