### ISSUE TITLE
Не работают трейлеры у дополнительных пользователей (managed users)

### ISSUE THREAD

**Issue by romanad** [amirotin/Kinopoisk.bundle#22]
OS Windows 10 x64
У добавленных пользователей  (managed users) в Plex Media Server во время просмотра трейлеров возникает ошибка сети:
(An error occurred trying to play "Трейлер (дублированный)".
Error code: s1001 (Network) )

![TRHehad 1](https://user-images.githubusercontent.com/26842711/77255431-5cfa3c00-6c78-11ea-9516-c0948b83c556.png)

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и возможно потребуется обновить метаданные. Сообщите пожалуйста, если проблема актуальна
