### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pendikeu** [amirotin/Kinopoisk.bundle#23]
**Описание ошибки**
После обновления PLEX до версии 4.22.2, плагин тянет с кинопоиска только название и год фильма.

**Шаги для воспроизведения ошибки**
1. Выбрать фильма в библиотеке
2. В правом верхнем углу, выбрать "Исправить сопоставление"
3. В меню выбрать Агент Кинопоиск 2.0, нажать на "поиск". После отображения результатов поиска - выбрать наиболее подходящий.
4. После выбора и обновления информации - отображается только "картинка(кадр из фильма)" вместо постера и название фильма.

**Ожидание**
Обычно информация подтягивалась с Кинопоиска и корректно обновлялась.

**Скриншоты**
Если есть возможность, приложите скриншот ошибки. (Как это сделать? Достаточно переместить нужные скриншоты в это текстовое поле https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests )

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Debian OMV 4.1.35-1 Arrakis
 - Chrome
 - Plex 4.22.2
 - HPGEN10OMV
 - Kinopoisk #STABLE-v2.0.7

**Дополнительная информация**
Добавьте любой другой контекст о проблеме здесь.

**Comment by glemag** [comment]
Абсолютно аналогичная проблема

- Plex 4.22.2
- Kinopoisk #STABLE-v2.0.7
- Synology DS414

**Comment by SergeyPLG** [comment]
Да, та же самая проблема:
Plex Версия 4.22.2
Kinopoisk #STABLE-v2.0.7
Пробовал разные комбинации настроек, ничего не помогает.

**Comment by Patricy** [comment]
Подтверждаю, та же проблема
Plex Версия 4.22.2
Kinopoisk #STABLE-v2.0.7

Помогает нажать "Исправить сопоставление" и поменять агента на TheMovieDatabase
Но хотелось бы кинопоиском и дальше пользоваться

**Comment by to03** [comment]
Как у всех проблема

    Plex 4.22.2
    Kinopoisk #STABLE-v2.0.7
    QNAP TS-453Be

**Comment by glemag** [comment]
"Исправить сопоставление" решает проблему, и данные подхватываются, но автоматом к сожалению нет при скачивании - не важно в каком виде фигурирует название файла.

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и возможно потребуется обновить метаданные.
