### ISSUE TITLE
[BUG] не подтягивает данные. название определяет верно.

### ISSUE THREAD

**Issue by Partizan7676** [amirotin/Kinopoisk.bundle#24]
Новые объекты имеют только название. более ничего. как прикрепить лог?

**Comment by bobzakh** [comment]
Поддерживаю тему, не подгружает постеры и описание фильма.

**Comment by dosikru** [comment]
+

**Comment by pixelinfinito** [comment]
Плюс +

**Comment by denber45** [comment]
+1

**Comment by landy2005** [comment]
+

**Comment by Free0wl** [comment]
+1

**Comment by Serka76** [comment]
+ и от меня , перестал работать :(

**Comment by nikolaevi** [comment]
Тоже самое. Ничего пе подтягивает.

**Comment by landy2005** [comment]
Исходя из того что я вижу (релиз 2.0.7):
https://github.com/amirotin/Kinopoisk.bundle/commit/507d8340d1289928f005ba9513e283cbc037834a

похоже на какой то разлад в среде разработчиков?..
меня смущают безусловная смена ссылок на репозиторий, и главное ссылок на донат некоему Ганута Алексей Владимирович (@ziemenz).
Хотя я также вижу появившуюся настройку, использовать разные репозитории.
Но по факту получается, что все Алексей итак внес изменения которые меняют ссылки на его собственные.

Это конечно не объясняет возникновение данной ошибки, но мне не очень нравится такое изменение без объяснения причин.

**Comment by Nickulous** [comment]
С сегодняшнего дня перестал подтягивать постеры и данные.

**Comment by EvelRus** [comment]
> Исходя из того что я вижу (релиз 2.0.7):
> [507d834](https://github.com/amirotin/Kinopoisk.bundle/commit/507d8340d1289928f005ba9513e283cbc037834a)
> 
> похоже на какой то разлад в среде разработчиков?..
> меня смущают безусловная смена ссылок на репозиторий, и главное ссылок на донат некоему Ганута Алексей Владимирович (@ziemenz).
> Хотя я также вижу появившуюся настройку, использовать разные репозитории.
> Но по факту получается, что все Алексей итак внес изменения которые меняют ссылки на его собственные.
> 
> Это конечно не объясняет возникновение данной ошибки, но мне не очень нравится такое изменение без объяснения причин.

Все согласовано с Артемом. Доступ к плагину передан "официально" )) Так что все в порядке )

**Comment by landy2005** [comment]
> Все согласовано с Артемом. Доступ к плагину передан "официально" )) Так что все в порядке )

тогда не совсем понятно зачем в настройках 2 репозитория.

Но ок, интересно кто то починит плагин?..
Я так понял все сломалось после (автоматического) обновления до 2.0.7.
Просто еще не у всех обновилось да и не часто добавляют новые фильмы, поэтому замечают не сразу.

**Comment by EvelRus** [comment]
Два, чтобы Вас не обидеть ))) Сразу видно, кто начал, кто подхватил ))

Не уверен, вроде как в последней версии плеске сменился API... Опять (

**Comment by dosikru** [comment]
А исправлять то когда планируете?
Совсем на карантине тут скучно.

**Comment by MikeVL** [comment]
+ Ничего пе подтягивает.

**Comment by Nickulous** [comment]
Все подтягивает. Отключите трейлеры в настройках плагина.

**Comment by Free0wl** [comment]
> Все подтягивает. Отключите трейлеры в настройках плагина.

+1

**Comment by rudre** [comment]
> Все подтягивает. Отключите трейлеры в настройках плагина.

Мне помогло, спасибо!

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, возможно потребуется обновить метаданные
