### ISSUE TITLE
[BUG] Перестал подтягивать данные (постер, описание, трейлеры и т.д.) для фильмов и сериалов

### ISSUE THREAD

**Issue by Nickulous** [amirotin/Kinopoisk.bundle#25]
**Описание ошибки**
При сопоставлении фильма с кинопоиском в поиске можно выбрать нужный фильм, но данные о нем не подтягиваются

**Шаги для вопроизведения ошибки**
1. Перейти в "Фильмы"
2. Нажать "Сопоставить"
3. Выбрать найденный фильм
4. Ошибка, данных нет

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Synology
 - Браузер любой
 - Версия PLEX 1.18.9.2571
 - Версия агента кинопоиск 2.0.7

**Comment by EvelRus** [comment]
Отключи трейлеры и все заработает.

**Comment by Nickulous** [comment]
В плагине? Отключил. Все равно не работает.

**Comment by Nickulous** [comment]
Вроде заработало. А с трейлерами теперь никак?

**Comment by EvelRus** [comment]
Пока нет (

**Comment by xes66** [comment]
отключение трейлов помогло.
вопрос не в тему- есть плагин для Плекса который фото каталогизирует? по геотегу, по содержимому или лицам?

**Comment by DmitrijsGribkovs** [comment]
Точно такаяже проблема. Ничего не работает
OS: FreeBSD-amd64
Kinopoisk #STABLE-v2.0.7

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и возможно потребуется обновить метаданные.
