### ISSUE TITLE
[BUG] Нет ни рейтинга, ни отзывов, ни русских трейлеров с кинопоиска

### ISSUE THREAD

**Issue by c1tru55** [amirotin/Kinopoisk.bundle#26]
OS: Synology DSM 6.2.2-24922 Update 5
PMS: 1.18.9.2571

Подключаемые модули:
![](http://i.imgur.com/Q3bNfE3.png)
Агенты:
![](http://i.imgur.com/AGybcyc.png)
При клике на `i` версия почему-то `2.0-DEVELOP`
![](http://i.imgur.com/1wSACbz.png)
Настройки агента:
![](http://i.imgur.com/8N4zpE5.png)
Настройки библиотеки:
![](http://i.imgur.com/CE5KazL.png)
После обновления метаданных - никаких данных из кинопоиска не наблюдается:
![](http://i.imgur.com/BuVNEGL.png)
![](http://i.imgur.com/tqxsAuP.png)

В `Управление -> Консоль` никаких ошибок вроде нет.

**Comment by DmitrijsGribkovs** [comment]
Точно такаяже проблема. Ничего не работает
OS: FreeBSD-amd64
Kinopoisk #STABLE-v2.0.7

**Comment by romanad** [comment]
Аналогичная ситуация, версия плагина последняя 2.0.7. 
Windows 10 x64.

**Comment by ikaygorodov** [comment]
Тоже самое. Synology 918+, 1019+, 916+ с последней версией DSM и Plex.
Хотелось бы понимать где можно посмотреть логи.

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и возможно потребуется обновить метаданные.

**Comment by romanad** [comment]
На QNAP:
1) Кинопоиск слетает после обновления Plex
2) Нет русских трейлеров
