### ISSUE TITLE
[BUG] Все метаданные сериалов заменились метаданными от сериала "И никого не стало" 2015

### ISSUE THREAD

**Issue by MonakhovK** [amirotin/Kinopoisk.bundle#30]
**Описание ошибки**
При попытке обновить все метаданные в библиотеке с сериалами - все метаданные были заменены на метаданные от сериала "И никого не стало" - 2015 (см. скриншот)
У меня такого сериала в базе даже нет.

**Шаги для вопроизведения ошибки**
1. Перейти в 'библиотеку PLEX'
2. Нажать '...' напротив с библиотекой с сериалами
3. Выбрать 'Управление метаданными' > 'обновить все метаданные'
4. Ошибка

**Ожидание**
Нормальной загрузки метаданных )

**Скриншоты**
![image](https://user-images.githubusercontent.com/46240852/82514267-22f1cd00-9b37-11ea-8d1a-b68269a083a2.png)

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Synology
 - Браузер: Chrome
 - Версия PLEX: 1.19.3.2831-181d9145d
 - Версия агента кинопоиск: v2.0.9 Stable

**Comment by ziemenz** [comment]
Свяжитесь пожалуйста со мной в Telegram: @ziemenz

**Comment by ziemenz** [comment]
В таких случаях необходимо заново сопоставить фильмы/сериалы

**Comment by sosed213** [comment]
Такая же проблема. При ручном сопоставлении любого фильмов.
