### ISSUE TITLE
[Feature request] Плагин не отображается как агент для сериалов

### ISSUE THREAD

**Issue by harvestnide** [amirotin/Kinopoisk.bundle#8]
С фильмами все нормально, но в сериалах просто нет опции включить его как агента для поиска

**Comment by armdan** [comment]
same here only on movies

**Comment by anvme** [comment]
> same here only on movies

Уже реализовано в плагине Кинопоиск по этой ссылке - https://github.com/ziemenz/Kinopoisk.bundle/issues

**Comment by anvme** [comment]
> С фильмами все нормально, но в сериалах просто нет опции включить его как агента для поиска

Уже реализовано в плагине Кинопоиск по этой ссылке - https://github.com/ziemenz/Kinopoisk.bundle/issues

**Comment by romanad** [comment]
same problem

**Comment by ziemenz** [comment]
Начиная с версии v.2.0.7 такой проблемы не наблюдается
