### ISSUE TITLE
[BUG] Описание и название фильмов вытаскивает на английском

### ISSUE THREAD

**Issue by vainamoinen787** [amirotin/Kinopoisk.bundle#9]
С сериалами все ок.
В настройках везде выбран русский

**Comment by anvme** [comment]
Проблема актуальная? Если да, прошу сообщить об этом и предоставить больше информации в новую ветку разработки плагина Кинопоиск - https://github.com/ziemenz/Kinopoisk.bundle/issues

**Comment by ziemenz** [comment]
На последней версии не удаётся повторить, нужно больше вводных.
Нужны версия плагина, версия PLEX Server, на какой ОС стоит.
Так же нужны имена файлов, которые криво подтягиваются, и желательно скрин настроек плагина и настроек библиотеки с фильмами

**Comment by ziemenz** [comment]
Выпущена версия 2.0.9, обновитесь и возможно потребуется обновить метаданные.
